openapi: 3.0.0
info:
  title: Subtitle Parser Plugin
  version: 1.0.0
paths:
  /api/parse-subtitle:
    get:
      summary: 解析视频字幕
      description: 根据视频 URL 获取不同语言的字幕
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
            example: "https://www.youtube.com/watch?v=gQEkCFzZfPA"
      responses:
        '200':
          description: 返回字幕信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      title:
                        type: string
                      subtitle_urls:
                        type: object
                        additionalProperties:
                          type: string
                        description: 字幕语言和对应的字幕 URL（例如：English, Korean, zh-CN）
                      url:
                        type: string
        '400':
          description: 请求参数错误
        '500':
          description: 服务器错误
